### PR TITLE
Fix 'WITH_FIFOS' flag handling for building

### PR DESCRIPTION
**Pull request by stoyan-shopov**

### CODE REVIEW

**Comment by stoyan-shopov** [comment]
Oops, I think I got this wrong. Actually, the trouble seems to only be a misplaced #ifdef. Will post an update

**Comment by mubes** [comment]
Hi Stoyan,

What problem are you trying to solve? Are you seeing some errors on build?

DAVE

**Comment by stoyan-shopov** [comment]
Sorry, I was getting a very obscure error due to a misplaced '#ifdef', the title is misleading. I just posted an update

**Comment by mubes** [comment]
Yep, I can see your issue now. I'll happily commit this. Please send me 
(to dave @ marples . net) your full name and email address and I'll add 
you to the contributors file too.

Ta!

DAVE

**Pull request merged**
