### PR TITLE
fix: macOS doesn’t support unnamed POSIX semaphores

### PR DESCRIPTION
**Pull request by bissonex**

### CODE REVIEW

**Comment by zyp** [comment]
This is the same issue that's fixed in Devel by 2ca431b with a different approach.

**Comment by bissonex** [comment]
Oh well. Should have checked before tracking that issue.

**Comment by zyp** [comment]
Sorry about it not being more obvious.

I also find hiding away recent changes in a «Devel» branch a bit unintuitive and have been arguing for letting development happen on main instead, so I hope we'll make some changes in that regard soon, before any more time is wasted fixing already solved problems.

**Comment by bissonex** [comment]
No problem, I am just glad this is fixed for everyone on macOS.

**Comment by mubes** [comment]
Yeah, we discussed this at stupid o'clock last night.  We'll move Main 
to become the Development-but-mostly-stable branch and use feature 
branches for unstable things. That should help avoid these kinds of 
'accidents'.  In any case, thanks for the contribution, it's appreciated 
and, as a side effect, is pushing us to fix a problem that's been around 
for a while.

Regards

DAVE

**Pull request closed without merging**
